### ISSUE TITLE
Schematic is incorrect.

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/SpotiFetch#3]
The given schematic doesn't work as expected. May be an issue with the connections.

_This issue must be completed before proceeding to the other issues._

### Maintainer
Advaith Rajan Nair

**Comment by SpaceCypher** [comment]
please assign

**Comment by Archit-Rode** [comment]
please assign

**Comment by Mrigank-J** [comment]
i will take it
working on it rn
