### ISSUE TITLE
Songs with long names are clipped.

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/SpotiFetch#4]
Long names do not fit on a screen 16 wide. Find a way to display the entire song name.

### Maintainer
Advaith Rajan Nair

**Comment by HackerGlory** [comment]
please assign me to this

**Comment by SpaceCypher** [comment]
please assign

**Comment by Advaith-RN** [comment]
> please assign me to this 
> 

@HackerGlory assigned

**Comment by Advaith-RN** [comment]
You can collect the hardware to test after the jam sesh

**Comment by SuchitraShankar07** [comment]
Please assign this to me

**Comment by HackerGlory** [comment]
i am moving on to resolve this, i hope you understand

**Comment by NishanHolla** [comment]
can i get assigned ?
